In [2]:
import numpy as np

In [58]:
#Ejercicio 1: 
if ar.ndim==1: print(ar,'Nº elementos',ar.shape)
elif ar.ndim>=1:print("Error")

[0 1 2 3 4 5] Nº elementos (6,)


In [3]:
#Ejercicio 2: 
ar2 = np.random.randint(0, 100,(5,5))
print(ar2)

[[11 14 52 77 24]
 [71 60 50 69 19]
 [95 11 97 73 79]
 [43 44 11  2 12]
 [28 32 67 40 79]]


In [154]:
#Ejercicio 3: 
ar3 = np.array([[99,2,4,6],[1,3,5,7]])
#print(ar3)
print('Total filas:',np.cumsum(ar3,axis=1), 'Total columnas:', np.cumsum(ar3,axis=0))

Total filas: [[ 99 101 105 111]
 [  1   4   9  16]] Total columnas: [[ 99   2   4   6]
 [100   5   9  13]]


In [7]:
#Ejercicio 4: 
ar4 = np.array([[99,2,4,6],[1,3,5,7]])
arc = np.corrcoef(ar4)
print(arc)

[[ 1.        -0.7524091]
 [-0.7524091  1.       ]]
